repos:
  - repo: local
    hooks:
      - id: legacy-import-guard
        name: Legacy shared_python import guard
        entry: python .github/scripts/check_legacy_imports.py
        language: system
        types: [python]
        pass_filenames: false
