services:
  fks_worker:
    build:
      context: .
      dockerfile: shared/shared_docker/templates/Dockerfile.python
    working_dir: /app/src
    command: ["bash", "-c", "cd /app/src && /venv/bin/python app.py"]
    environment:
      TZ: America/Toronto
      SERVICE_PORT: 4600
      WORKER_SERVICE_PORT: 4600
      PYTHONPATH: /app/src
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "4600:4600"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/app/logs
    networks: [fks_net]
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4600/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    networks: [fks_net]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep worker || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 20s

volumes:
  redis_data:

networks:
  fks_net:
    external: true