services:
  fks_worker:
    build:
      context: .
      dockerfile: Dockerfile
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep worker || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 20s

networks:
  fks_net:
    name: fks_net