name: Build & Publish Core Images

on:
  push:
    branches: [ main, master ]
    paths:
      - 'fks_master/docker-compose.yml'
      - 'fks_master/deployment/docker/**'
      - 'fks_master/src/**'
      - 'fks_master/package.json'
      - '.github/workflows/docker-images-build.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, worker, data, engine, transformer, web, nginx]
    env:
      DOCKER_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_NAMESPACE == '' && 'nuniesmith' || env.DOCKER_NAMESPACE }}/fks:${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: fks_master
          file: fks_master/deployment/docker/Dockerfile
          build-args: |
            SERVICE_TYPE=${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
