name: Monitoring Config Validate

on:
  push:
    branches: [ main, master ]
    paths:
      - 'fks_master/config/monitoring/**'
      - '.github/workflows/monitoring-config-validate.yml'
  pull_request:
    paths:
      - 'fks_master/config/monitoring/**'
      - '.github/workflows/monitoring-config-validate.yml'
  workflow_dispatch: {}

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download promtool
        run: |
          PROM_VERSION="v2.55.0"
          curl -sSL -o prom.tar.gz https://github.com/prometheus/prometheus/releases/download/${PROM_VERSION}/prometheus-${PROM_VERSION#v}.linux-amd64.tar.gz
          tar -xzf prom.tar.gz
          sudo mv prometheus-${PROM_VERSION#v}.linux-amd64/promtool /usr/local/bin/promtool
          promtool --version

      - name: Validate Prometheus config
        run: |
          promtool check config fks_master/config/monitoring/prometheus/prometheus.yml

      - name: Validate rules
        run: |
          promtool check rules fks_master/config/monitoring/prometheus/rules/*.yml

      - name: Templated summary
        run: echo "Prometheus configuration and rules validated successfully." >> $GITHUB_STEP_SUMMARY
